// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The analysis resource.
public struct Analysis: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the analysis.
  /// Format:
  /// projects/{project}/locations/{location}/conversations/{conversation}/analyses/{analysis}
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which the analysis was requested.
  public var requestTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time at which the analysis was created, which occurs when
  /// the long-running operation completes.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The result of the analysis, which is populated when the
  /// analysis finishes.
  public var analysisResult: AnalysisResult? = nil

  /// To select the annotators to run and the phrase matchers to use
  /// (if any). If not specified, all annotators will be run.
  public var annotatorSelector: AnnotatorSelector? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Analysis`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Analysis().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let requestTime = CodingKeys(stringValue: "requestTime")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let analysisResult = CodingKeys(stringValue: "analysisResult")
    static let annotatorSelector = CodingKeys(stringValue: "annotatorSelector")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "requestTime",
      "createTime",
      "analysisResult",
      "annotatorSelector",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.requestTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .requestTime)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.analysisResult = try container.decodeIfPresent(
      AnalysisResult.self, forKey: .analysisResult)
    self.annotatorSelector = try container.decodeIfPresent(
      AnnotatorSelector.self, forKey: .annotatorSelector)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.requestTime, forKey: .requestTime)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.analysisResult, forKey: .analysisResult)
    try container.encodeIfPresent(self.annotatorSelector, forKey: .annotatorSelector)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.Analysis"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
