// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The result of an analysis.
public struct AnalysisResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The time at which the analysis ended.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Metadata discovered during analysis.
  public var metadata: OneOf_Metadata? = nil

  /// Initialize a new instance of `AnalysisResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalysisResult().with { $0.callAnalysisMetadata = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case callAnalysisMetadata = "callAnalysisMetadata"
    case endTime = "endTime"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.endTime = try container.decodeIfPresent(GoogleCloudWkt.Timestamp.self, forKey: .endTime)

    var metadata: OneOf_Metadata? = nil
    let metadataCheckAndSet = {
      if metadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'metadata'"))
      }
      metadata = $0
    }
    if let callAnalysisMetadata = try container.decodeIfPresent(
      AnalysisResult.CallAnalysisMetadata?.self, forKey: .callAnalysisMetadata)
    {
      try metadataCheckAndSet(.callAnalysisMetadata(callAnalysisMetadata))
    }
    self.metadata = metadata
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.endTime, forKey: .endTime)

    if let choice = self.metadata {
      switch choice {
      case .callAnalysisMetadata(let value):
        try container.encode(value, forKey: .callAnalysisMetadata)
      }
    }
  }

  /// Call-specific metadata created during analysis.
  public struct CallAnalysisMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A list of call annotations that apply to this call.
    public var annotations: [CallAnnotation] = []

    /// All the entities in the call.
    public var entities: [Swift.String: Entity] = [:]

    /// Overall conversation-level sentiment for each channel of the call.
    public var sentiments: [ConversationLevelSentiment] = []

    /// Overall conversation-level silence during the call.
    public var silence: ConversationLevelSilence? = nil

    /// All the matched intents in the call.
    public var intents: [Swift.String: Intent] = [:]

    /// All the matched phrase matchers in the call.
    public var phraseMatchers: [Swift.String: PhraseMatchData] = [:]

    /// Overall conversation-level issue modeling result.
    public var issueModelResult: IssueModelResult? = nil

    /// Results of scoring QaScorecards.
    public var qaScorecardResults: [QaScorecardResult] = []

    /// Initialize a new instance of `CallAnalysisMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CallAnalysisMetadata().with { $0.annotations = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.AnalysisResult.CallAnalysisMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Metadata discovered during analysis.
  public enum OneOf_Metadata: Codable, Equatable, Sendable {
    /// Call-specific metadata created by the analysis.
    indirect case callAnalysisMetadata(AnalysisResult.CallAnalysisMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.AnalysisResult"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
