// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The CCAI Insights project wide analysis rule. This rule will be applied to
/// all conversations that match the filter defined in the rule. For a
/// conversation matches the filter, the annotators specified in the rule will be
/// run. If a conversation matches multiple rules, a union of all the annotators
/// will be run. One project can have multiple analysis rules.
public struct AnalysisRule: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the analysis rule.
  /// Format:
  /// projects/{project}/locations/{location}/analysisRules/{analysis_rule}
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which this analysis rule was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The most recent time at which this analysis rule was updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Display Name of the analysis rule.
  public var displayName: Swift.String? = nil

  /// Filter for the conversations that should apply this analysis
  /// rule. An empty filter means this analysis rule applies to all
  /// conversations.
  public var conversationFilter: Swift.String = Swift.String()

  /// Selector of annotators to run and the phrase matchers to use for
  /// conversations that matches the conversation_filter. If not specified, NO
  /// annotators will be run.
  public var annotatorSelector: AnnotatorSelector? = nil

  /// Percentage of conversations that we should apply this analysis setting
  /// automatically, between [0, 1]. For example, 0.1 means 10%. Conversations
  /// are sampled in a determenestic way. The original runtime_percentage &
  /// upload percentage will be replaced by defining filters on the conversation.
  public var analysisPercentage: Swift.Double = Swift.Double()

  /// If true, apply this rule to conversations. Otherwise, this rule is
  /// inactive and saved as a draft.
  public var active: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AnalysisRule`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalysisRule().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let conversationFilter = CodingKeys(stringValue: "conversationFilter")
    static let annotatorSelector = CodingKeys(stringValue: "annotatorSelector")
    static let analysisPercentage = CodingKeys(stringValue: "analysisPercentage")
    static let active = CodingKeys(stringValue: "active")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "displayName",
      "conversationFilter",
      "annotatorSelector",
      "analysisPercentage",
      "active",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.displayName = try container.decodeIfPresent(Swift.String.self, forKey: .displayName)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .conversationFilter) {
      self.conversationFilter = value
    }
    self.annotatorSelector = try container.decodeIfPresent(
      AnnotatorSelector.self, forKey: .annotatorSelector)
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .analysisPercentage) {
      self.analysisPercentage = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .active) {
      self.active = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.displayName, forKey: .displayName)
    try container.encode(self.conversationFilter, forKey: .conversationFilter)
    try container.encodeIfPresent(self.annotatorSelector, forKey: .annotatorSelector)
    try container.encode(self.analysisPercentage, forKey: .analysisPercentage)
    try container.encode(self.active, forKey: .active)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.AnalysisRule"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
