// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// A point in a conversation that marks the start or the end of an annotation.
public struct AnnotationBoundary: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The index in the sequence of transcribed pieces of the conversation where
  /// the boundary is located. This index starts at zero.
  public var transcriptIndex: Swift.Int32 = Swift.Int32()

  /// A detailed boundary, which describes a more specific point.
  public var detailedBoundary: OneOf_DetailedBoundary? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `AnnotationBoundary`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnnotationBoundary().with { $0.wordIndex = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let wordIndex = CodingKeys(stringValue: "wordIndex")
    static let transcriptIndex = CodingKeys(stringValue: "transcriptIndex")

    static let _knownKeys: Set<Swift.String> = [
      "wordIndex",
      "transcriptIndex",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .transcriptIndex) {
      self.transcriptIndex = value
    }

    var detailedBoundary: OneOf_DetailedBoundary? = nil
    let detailedBoundaryCheckAndSet = {
      if detailedBoundary != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'detailedBoundary'"))
      }
      detailedBoundary = $0
    }
    if let wordIndex = try container.decodeIfPresent(Swift.Int32.self, forKey: .wordIndex) {
      try detailedBoundaryCheckAndSet(.wordIndex(wordIndex))
    }
    self.detailedBoundary = detailedBoundary
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.transcriptIndex, forKey: .transcriptIndex)

    if let choice = self.detailedBoundary {
      switch choice {
      case .wordIndex(let value):
        try container.encode(value, forKey: .wordIndex)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A detailed boundary, which describes a more specific point.
  public enum OneOf_DetailedBoundary: Codable, Equatable, Sendable {
    /// The word index of this boundary with respect to the first word in the
    /// transcript piece. This index starts at zero.
    case wordIndex(Swift.Int32)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.AnnotationBoundary"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
