// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Metadata for the BulkDownloadFeedbackLabel endpoint.
public struct BulkDownloadFeedbackLabelsMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The time the operation was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time the operation finished running.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Output only. The original request for download.
  public var request: BulkDownloadFeedbackLabelsRequest? = nil

  /// Partial errors during ingest operation that might cause the operation
  /// output to be incomplete.
  public var partialErrors: [GoogleRpc.Status] = []

  /// Output only. Statistics for BulkDownloadFeedbackLabels operation.
  public var downloadStats: BulkDownloadFeedbackLabelsMetadata.DownloadStats? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BulkDownloadFeedbackLabelsMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BulkDownloadFeedbackLabelsMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let request = CodingKeys(stringValue: "request")
    static let partialErrors = CodingKeys(stringValue: "partialErrors")
    static let downloadStats = CodingKeys(stringValue: "downloadStats")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "endTime",
      "request",
      "partialErrors",
      "downloadStats",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    self.request = try container.decodeIfPresent(
      BulkDownloadFeedbackLabelsRequest.self, forKey: .request)
    if let value = try container.decodeIfPresent([GoogleRpc.Status].self, forKey: .partialErrors) {
      self.partialErrors = value
    }
    self.downloadStats = try container.decodeIfPresent(
      BulkDownloadFeedbackLabelsMetadata.DownloadStats.self, forKey: .downloadStats)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encodeIfPresent(self.request, forKey: .request)
    try container.encode(self.partialErrors, forKey: .partialErrors)
    try container.encodeIfPresent(self.downloadStats, forKey: .downloadStats)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Statistics for BulkDownloadFeedbackLabels operation.
  public struct DownloadStats: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The number of objects processed during the download operation.
    public var processedObjectCount: Swift.Int32 = Swift.Int32()

    /// The number of new feedback labels downloaded during this operation.
    /// Different from "processed" because some labels might not be downloaded
    /// because an error.
    public var successfulDownloadCount: Swift.Int32 = Swift.Int32()

    /// Total number of files written to the provided Cloud Storage bucket.
    public var totalFilesWritten: Swift.Int32 = Swift.Int32()

    /// Output only. Full name of the files written to Cloud storage.
    public var fileNames: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DownloadStats`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DownloadStats().with { $0.processedObjectCount = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let processedObjectCount = CodingKeys(stringValue: "processedObjectCount")
      static let successfulDownloadCount = CodingKeys(stringValue: "successfulDownloadCount")
      static let totalFilesWritten = CodingKeys(stringValue: "totalFilesWritten")
      static let fileNames = CodingKeys(stringValue: "fileNames")

      static let _knownKeys: Set<Swift.String> = [
        "processedObjectCount",
        "successfulDownloadCount",
        "totalFilesWritten",
        "fileNames",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .processedObjectCount)
      {
        self.processedObjectCount = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .successfulDownloadCount)
      {
        self.successfulDownloadCount = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .totalFilesWritten) {
        self.totalFilesWritten = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .fileNames) {
        self.fileNames = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.processedObjectCount, forKey: .processedObjectCount)
      try container.encode(self.successfulDownloadCount, forKey: .successfulDownloadCount)
      try container.encode(self.totalFilesWritten, forKey: .totalFilesWritten)
      try container.encode(self.fileNames, forKey: .fileNames)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.BulkDownloadFeedbackLabelsMetadata.DownloadStats"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.contactcenterinsights.v1.BulkDownloadFeedbackLabelsMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
