// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The response for calculating conversation statistics.
public struct CalculateStatsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The average duration of all conversations. The average is calculated using
  /// only conversations that have a time duration.
  public var averageDuration: GoogleCloudWkt.Duration? = nil

  /// The average number of turns per conversation.
  public var averageTurnCount: Swift.Int32 = Swift.Int32()

  /// The total number of conversations.
  public var conversationCount: Swift.Int32 = Swift.Int32()

  /// A map associating each smart highlighter display name with its respective
  /// number of matches in the set of conversations.
  public var smartHighlighterMatches: [Swift.String: Swift.Int32] = [:]

  /// A map associating each custom highlighter resource name with its respective
  /// number of matches in the set of conversations.
  public var customHighlighterMatches: [Swift.String: Swift.Int32] = [:]

  /// A map associating each issue resource name with its respective number of
  /// matches in the set of conversations. Key has the format:
  /// `projects/<Project-ID>/locations/<Location-ID>/issueModels/<Issue-Model-ID>/issues/<Issue-ID>`
  /// Deprecated, use `issue_matches_stats` field instead.
  @available(*, deprecated)
  public var issueMatches: [Swift.String: Swift.Int32] = [:]

  /// A map associating each issue resource name with its respective number of
  /// matches in the set of conversations. Key has the format:
  /// `projects/<Project-ID>/locations/<Location-ID>/issueModels/<Issue-Model-ID>/issues/<Issue-ID>`
  public var issueMatchesStats: [Swift.String: IssueModelLabelStats.IssueStats] = [:]

  /// A time series representing the count of conversations created over time
  /// that match that requested filter criteria.
  public var conversationCountTimeSeries: CalculateStatsResponse.TimeSeries? = nil

  /// Initialize a new instance of `CalculateStatsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CalculateStatsResponse().with { $0.averageDuration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A time series representing conversations over time.
  public struct TimeSeries: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The duration of each interval.
    public var intervalDuration: GoogleCloudWkt.Duration? = nil

    /// An ordered list of intervals from earliest to latest, where each interval
    /// represents the number of conversations that transpired during the time
    /// window.
    public var points: [CalculateStatsResponse.TimeSeries.Interval] = []

    /// Initialize a new instance of `TimeSeries`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeSeries().with { $0.intervalDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// A single interval in a time series.
    public struct Interval: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The start time of this interval.
      public var startTime: GoogleCloudWkt.Timestamp? = nil

      /// The number of conversations created in this interval.
      public var conversationCount: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `Interval`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Interval().with { $0.startTime = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.contactcenterinsights.v1.CalculateStatsResponse.TimeSeries.Interval"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.CalculateStatsResponse.TimeSeries"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.CalculateStatsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
