// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The response for calculating conversation statistics.
public struct CalculateStatsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The average duration of all conversations. The average is calculated using
  /// only conversations that have a time duration.
  public var averageDuration: GoogleWKT.Duration? = nil

  /// The average number of turns per conversation.
  public var averageTurnCount: Swift.Int32 = Swift.Int32()

  /// The total number of conversations.
  public var conversationCount: Swift.Int32 = Swift.Int32()

  /// A map associating each smart highlighter display name with its respective
  /// number of matches in the set of conversations.
  public var smartHighlighterMatches: [Swift.String: Swift.Int32] = [:]

  /// A map associating each custom highlighter resource name with its respective
  /// number of matches in the set of conversations.
  public var customHighlighterMatches: [Swift.String: Swift.Int32] = [:]

  /// A map associating each issue resource name with its respective number of
  /// matches in the set of conversations. Key has the format:
  /// `projects/<Project-ID>/locations/<Location-ID>/issueModels/<Issue-Model-ID>/issues/<Issue-ID>`
  /// Deprecated, use `issue_matches_stats` field instead.
  @available(*, deprecated)
  public var issueMatches: [Swift.String: Swift.Int32] = [:]

  /// A map associating each issue resource name with its respective number of
  /// matches in the set of conversations. Key has the format:
  /// `projects/<Project-ID>/locations/<Location-ID>/issueModels/<Issue-Model-ID>/issues/<Issue-ID>`
  public var issueMatchesStats: [Swift.String: IssueModelLabelStats.IssueStats] = [:]

  /// A time series representing the count of conversations created over time
  /// that match that requested filter criteria.
  public var conversationCountTimeSeries: CalculateStatsResponse.TimeSeries? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CalculateStatsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CalculateStatsResponse().with { $0.averageDuration = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let averageDuration = CodingKeys(stringValue: "averageDuration")
    static let averageTurnCount = CodingKeys(stringValue: "averageTurnCount")
    static let conversationCount = CodingKeys(stringValue: "conversationCount")
    static let smartHighlighterMatches = CodingKeys(stringValue: "smartHighlighterMatches")
    static let customHighlighterMatches = CodingKeys(stringValue: "customHighlighterMatches")
    static let issueMatches = CodingKeys(stringValue: "issueMatches")
    static let issueMatchesStats = CodingKeys(stringValue: "issueMatchesStats")
    static let conversationCountTimeSeries = CodingKeys(stringValue: "conversationCountTimeSeries")

    static let _knownKeys: Set<Swift.String> = [
      "averageDuration",
      "averageTurnCount",
      "conversationCount",
      "smartHighlighterMatches",
      "customHighlighterMatches",
      "issueMatches",
      "issueMatchesStats",
      "conversationCountTimeSeries",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.averageDuration = try container.decodeIfPresent(
      GoogleWKT.Duration.self, forKey: .averageDuration)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .averageTurnCount) {
      self.averageTurnCount = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .conversationCount) {
      self.conversationCount = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.Int32].self, forKey: .smartHighlighterMatches)
    {
      self.smartHighlighterMatches = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.Int32].self, forKey: .customHighlighterMatches)
    {
      self.customHighlighterMatches = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.Int32].self, forKey: .issueMatches)
    {
      self.issueMatches = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: IssueModelLabelStats.IssueStats].self, forKey: .issueMatchesStats)
    {
      self.issueMatchesStats = value
    }
    self.conversationCountTimeSeries = try container.decodeIfPresent(
      CalculateStatsResponse.TimeSeries.self, forKey: .conversationCountTimeSeries)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.averageDuration, forKey: .averageDuration)
    try container.encode(self.averageTurnCount, forKey: .averageTurnCount)
    try container.encode(self.conversationCount, forKey: .conversationCount)
    try container.encode(self.smartHighlighterMatches, forKey: .smartHighlighterMatches)
    try container.encode(self.customHighlighterMatches, forKey: .customHighlighterMatches)
    try container.encode(self.issueMatches, forKey: .issueMatches)
    try container.encode(self.issueMatchesStats, forKey: .issueMatchesStats)
    try container.encodeIfPresent(
      self.conversationCountTimeSeries, forKey: .conversationCountTimeSeries)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// A time series representing conversations over time.
  public struct TimeSeries: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The duration of each interval.
    public var intervalDuration: GoogleWKT.Duration? = nil

    /// An ordered list of intervals from earliest to latest, where each interval
    /// represents the number of conversations that transpired during the time
    /// window.
    public var points: [CalculateStatsResponse.TimeSeries.Interval] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `TimeSeries`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = TimeSeries().with { $0.intervalDuration = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let intervalDuration = CodingKeys(stringValue: "intervalDuration")
      static let points = CodingKeys(stringValue: "points")

      static let _knownKeys: Set<Swift.String> = [
        "intervalDuration",
        "points",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.intervalDuration = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .intervalDuration)
      if let value = try container.decodeIfPresent(
        [CalculateStatsResponse.TimeSeries.Interval].self, forKey: .points)
      {
        self.points = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.intervalDuration, forKey: .intervalDuration)
      try container.encode(self.points, forKey: .points)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// A single interval in a time series.
    public struct Interval: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The start time of this interval.
      public var startTime: GoogleWKT.Timestamp? = nil

      /// The number of conversations created in this interval.
      public var conversationCount: Swift.Int32 = Swift.Int32()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Interval`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Interval().with { $0.startTime = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let startTime = CodingKeys(stringValue: "startTime")
        static let conversationCount = CodingKeys(stringValue: "conversationCount")

        static let _knownKeys: Set<Swift.String> = [
          "startTime",
          "conversationCount",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.startTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .startTime)
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .conversationCount) {
          self.conversationCount = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.startTime, forKey: .startTime)
        try container.encode(self.conversationCount, forKey: .conversationCount)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.contactcenterinsights.v1.CalculateStatsResponse.TimeSeries.Interval"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.CalculateStatsResponse.TimeSeries"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.CalculateStatsResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
