// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A piece of metadata that applies to a window of a call.
public struct CallAnnotation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The channel of the audio where the annotation occurs. For single-channel
  /// audio, this field is not populated.
  public var channelTag: Swift.Int32 = Swift.Int32()

  /// The boundary in the conversation where the annotation starts, inclusive.
  public var annotationStartBoundary: AnnotationBoundary? = nil

  /// The boundary in the conversation where the annotation ends, inclusive.
  public var annotationEndBoundary: AnnotationBoundary? = nil

  /// The data in the annotation.
  public var data: OneOf_Data? = nil

  /// Initialize a new instance of `CallAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CallAnnotation().with { $0.interruptionData = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case interruptionData = "interruptionData"
    case sentimentData = "sentimentData"
    case silenceData = "silenceData"
    case holdData = "holdData"
    case entityMentionData = "entityMentionData"
    case intentMatchData = "intentMatchData"
    case phraseMatchData = "phraseMatchData"
    case issueMatchData = "issueMatchData"
    case channelTag = "channelTag"
    case annotationStartBoundary = "annotationStartBoundary"
    case annotationEndBoundary = "annotationEndBoundary"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.channelTag = try container.decode(Swift.Int32.self, forKey: .channelTag)
    self.annotationStartBoundary = try container.decodeIfPresent(
      AnnotationBoundary.self, forKey: .annotationStartBoundary)
    self.annotationEndBoundary = try container.decodeIfPresent(
      AnnotationBoundary.self, forKey: .annotationEndBoundary)

    var data: OneOf_Data? = nil
    let dataCheckAndSet = {
      if data != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'data'"
          ))
      }
      data = $0
    }
    if let interruptionData = try container.decodeIfPresent(
      InterruptionData?.self, forKey: .interruptionData)
    {
      try dataCheckAndSet(.interruptionData(interruptionData))
    }
    if let sentimentData = try container.decodeIfPresent(
      SentimentData?.self, forKey: .sentimentData)
    {
      try dataCheckAndSet(.sentimentData(sentimentData))
    }
    if let silenceData = try container.decodeIfPresent(SilenceData?.self, forKey: .silenceData) {
      try dataCheckAndSet(.silenceData(silenceData))
    }
    if let holdData = try container.decodeIfPresent(HoldData?.self, forKey: .holdData) {
      try dataCheckAndSet(.holdData(holdData))
    }
    if let entityMentionData = try container.decodeIfPresent(
      EntityMentionData?.self, forKey: .entityMentionData)
    {
      try dataCheckAndSet(.entityMentionData(entityMentionData))
    }
    if let intentMatchData = try container.decodeIfPresent(
      IntentMatchData?.self, forKey: .intentMatchData)
    {
      try dataCheckAndSet(.intentMatchData(intentMatchData))
    }
    if let phraseMatchData = try container.decodeIfPresent(
      PhraseMatchData?.self, forKey: .phraseMatchData)
    {
      try dataCheckAndSet(.phraseMatchData(phraseMatchData))
    }
    if let issueMatchData = try container.decodeIfPresent(
      IssueMatchData?.self, forKey: .issueMatchData)
    {
      try dataCheckAndSet(.issueMatchData(issueMatchData))
    }
    self.data = data
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.channelTag, forKey: .channelTag)
    try container.encode(self.annotationStartBoundary, forKey: .annotationStartBoundary)
    try container.encode(self.annotationEndBoundary, forKey: .annotationEndBoundary)

    if let choice = self.data {
      switch choice {
      case .interruptionData(let value):
        try container.encode(value, forKey: .interruptionData)
      case .sentimentData(let value):
        try container.encode(value, forKey: .sentimentData)
      case .silenceData(let value):
        try container.encode(value, forKey: .silenceData)
      case .holdData(let value):
        try container.encode(value, forKey: .holdData)
      case .entityMentionData(let value):
        try container.encode(value, forKey: .entityMentionData)
      case .intentMatchData(let value):
        try container.encode(value, forKey: .intentMatchData)
      case .phraseMatchData(let value):
        try container.encode(value, forKey: .phraseMatchData)
      case .issueMatchData(let value):
        try container.encode(value, forKey: .issueMatchData)
      }
    }
  }

  /// The data in the annotation.
  public enum OneOf_Data: Codable, Equatable, Sendable {
    /// Data specifying an interruption.
    indirect case interruptionData(InterruptionData?)
    /// Data specifying sentiment.
    indirect case sentimentData(SentimentData?)
    /// Data specifying silence.
    indirect case silenceData(SilenceData?)
    /// Data specifying a hold.
    indirect case holdData(HoldData?)
    /// Data specifying an entity mention.
    indirect case entityMentionData(EntityMentionData?)
    /// Data specifying an intent match.
    indirect case intentMatchData(IntentMatchData?)
    /// Data specifying a phrase match.
    indirect case phraseMatchData(PhraseMatchData?)
    /// Data specifying an issue match.
    indirect case issueMatchData(IssueMatchData?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.CallAnnotation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
