// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class ContactCenterInsightsLogging: ContactCenterInsightsStub {
    let inner: any ContactCenterInsightsStub
    let logger: Logger

    public init(_ inner: any ContactCenterInsightsStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-contactcenterinsights-v1"
      logger[metadataKey: "gcp.client.service"] = "contactcenterinsights"
      logger[metadataKey: "gcp.experimental.swift.client"] = "ContactCenterInsights"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createConversation(
      request: CreateConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Conversation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createConversation",
        action: {
          (r: CreateConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Conversation
          in
          return try await self.inner.createConversation(request: r, options: o)
        })
    }

    public func uploadConversation(
      request: UploadConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "uploadConversation",
        action: {
          (r: UploadConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.uploadConversation(request: r, options: o)
        })
    }

    public func updateConversation(
      request: UpdateConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Conversation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateConversation",
        action: {
          (r: UpdateConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Conversation
          in
          return try await self.inner.updateConversation(request: r, options: o)
        })
    }

    public func getConversation(
      request: GetConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Conversation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getConversation",
        action: {
          (r: GetConversationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Conversation
          in
          return try await self.inner.getConversation(request: r, options: o)
        })
    }

    public func listConversations(
      request: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListConversationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listConversations",
        action: {
          (r: ListConversationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListConversationsResponse
          in
          return try await self.inner.listConversations(request: r, options: o)
        })
    }

    public func deleteConversation(
      request: DeleteConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteConversation",
        action: {
          (r: DeleteConversationRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteConversation(request: r, options: o)
        })
    }

    public func createAnalysis(
      request: CreateAnalysisRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAnalysis",
        action: {
          (r: CreateAnalysisRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAnalysis(request: r, options: o)
        })
    }

    public func getAnalysis(
      request: GetAnalysisRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Analysis {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAnalysis",
        action: {
          (r: GetAnalysisRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Analysis
          in
          return try await self.inner.getAnalysis(request: r, options: o)
        })
    }

    public func listAnalyses(
      request: ListAnalysesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListAnalysesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAnalyses",
        action: {
          (r: ListAnalysesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListAnalysesResponse
          in
          return try await self.inner.listAnalyses(request: r, options: o)
        })
    }

    public func deleteAnalysis(
      request: DeleteAnalysisRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAnalysis",
        action: {
          (r: DeleteAnalysisRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAnalysis(request: r, options: o)
        })
    }

    public func bulkAnalyzeConversations(
      request: BulkAnalyzeConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "bulkAnalyzeConversations",
        action: {
          (r: BulkAnalyzeConversationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.bulkAnalyzeConversations(request: r, options: o)
        })
    }

    public func bulkDeleteConversations(
      request: BulkDeleteConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "bulkDeleteConversations",
        action: {
          (r: BulkDeleteConversationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.bulkDeleteConversations(request: r, options: o)
        })
    }

    public func ingestConversations(
      request: IngestConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "ingestConversations",
        action: {
          (r: IngestConversationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.ingestConversations(request: r, options: o)
        })
    }

    public func exportInsightsData(
      request: ExportInsightsDataRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportInsightsData",
        action: {
          (r: ExportInsightsDataRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportInsightsData(request: r, options: o)
        })
    }

    public func createIssueModel(
      request: CreateIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createIssueModel",
        action: {
          (r: CreateIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createIssueModel(request: r, options: o)
        })
    }

    public func updateIssueModel(
      request: UpdateIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.IssueModel {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIssueModel",
        action: {
          (r: UpdateIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.IssueModel
          in
          return try await self.inner.updateIssueModel(request: r, options: o)
        })
    }

    public func getIssueModel(
      request: GetIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.IssueModel {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIssueModel",
        action: {
          (r: GetIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.IssueModel
          in
          return try await self.inner.getIssueModel(request: r, options: o)
        })
    }

    public func listIssueModels(
      request: ListIssueModelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListIssueModelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIssueModels",
        action: {
          (r: ListIssueModelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListIssueModelsResponse
          in
          return try await self.inner.listIssueModels(request: r, options: o)
        })
    }

    public func deleteIssueModel(
      request: DeleteIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIssueModel",
        action: {
          (r: DeleteIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteIssueModel(request: r, options: o)
        })
    }

    public func deployIssueModel(
      request: DeployIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deployIssueModel",
        action: {
          (r: DeployIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deployIssueModel(request: r, options: o)
        })
    }

    public func undeployIssueModel(
      request: UndeployIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeployIssueModel",
        action: {
          (r: UndeployIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.undeployIssueModel(request: r, options: o)
        })
    }

    public func exportIssueModel(
      request: ExportIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportIssueModel",
        action: {
          (r: ExportIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.exportIssueModel(request: r, options: o)
        })
    }

    public func importIssueModel(
      request: ImportIssueModelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "importIssueModel",
        action: {
          (r: ImportIssueModelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.importIssueModel(request: r, options: o)
        })
    }

    public func getIssue(
      request: GetIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Issue {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIssue",
        action: {
          (r: GetIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Issue
          in
          return try await self.inner.getIssue(request: r, options: o)
        })
    }

    public func listIssues(
      request: ListIssuesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListIssuesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listIssues",
        action: {
          (r: ListIssuesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListIssuesResponse
          in
          return try await self.inner.listIssues(request: r, options: o)
        })
    }

    public func updateIssue(
      request: UpdateIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Issue {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateIssue",
        action: {
          (r: UpdateIssueRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Issue
          in
          return try await self.inner.updateIssue(request: r, options: o)
        })
    }

    public func deleteIssue(
      request: DeleteIssueRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteIssue",
        action: { (r: DeleteIssueRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteIssue(request: r, options: o)
        })
    }

    public func calculateIssueModelStats(
      request: CalculateIssueModelStatsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.CalculateIssueModelStatsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "calculateIssueModelStats",
        action: {
          (r: CalculateIssueModelStatsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.CalculateIssueModelStatsResponse
          in
          return try await self.inner.calculateIssueModelStats(request: r, options: o)
        })
    }

    public func createPhraseMatcher(
      request: CreatePhraseMatcherRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.PhraseMatcher {
      try await self._intercept(
        request: request,
        options: options,
        name: "createPhraseMatcher",
        action: {
          (r: CreatePhraseMatcherRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.PhraseMatcher
          in
          return try await self.inner.createPhraseMatcher(request: r, options: o)
        })
    }

    public func getPhraseMatcher(
      request: GetPhraseMatcherRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.PhraseMatcher {
      try await self._intercept(
        request: request,
        options: options,
        name: "getPhraseMatcher",
        action: {
          (r: GetPhraseMatcherRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.PhraseMatcher
          in
          return try await self.inner.getPhraseMatcher(request: r, options: o)
        })
    }

    public func listPhraseMatchers(
      request: ListPhraseMatchersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListPhraseMatchersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listPhraseMatchers",
        action: {
          (r: ListPhraseMatchersRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListPhraseMatchersResponse
          in
          return try await self.inner.listPhraseMatchers(request: r, options: o)
        })
    }

    public func deletePhraseMatcher(
      request: DeletePhraseMatcherRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deletePhraseMatcher",
        action: {
          (r: DeletePhraseMatcherRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deletePhraseMatcher(request: r, options: o)
        })
    }

    public func updatePhraseMatcher(
      request: UpdatePhraseMatcherRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.PhraseMatcher {
      try await self._intercept(
        request: request,
        options: options,
        name: "updatePhraseMatcher",
        action: {
          (r: UpdatePhraseMatcherRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.PhraseMatcher
          in
          return try await self.inner.updatePhraseMatcher(request: r, options: o)
        })
    }

    public func calculateStats(
      request: CalculateStatsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.CalculateStatsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "calculateStats",
        action: {
          (r: CalculateStatsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.CalculateStatsResponse
          in
          return try await self.inner.calculateStats(request: r, options: o)
        })
    }

    public func getSettings(
      request: GetSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Settings {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSettings",
        action: {
          (r: GetSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Settings
          in
          return try await self.inner.getSettings(request: r, options: o)
        })
    }

    public func updateSettings(
      request: UpdateSettingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.Settings {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSettings",
        action: {
          (r: UpdateSettingsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.Settings
          in
          return try await self.inner.updateSettings(request: r, options: o)
        })
    }

    public func createAnalysisRule(
      request: CreateAnalysisRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.AnalysisRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAnalysisRule",
        action: {
          (r: CreateAnalysisRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.AnalysisRule
          in
          return try await self.inner.createAnalysisRule(request: r, options: o)
        })
    }

    public func getAnalysisRule(
      request: GetAnalysisRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.AnalysisRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAnalysisRule",
        action: {
          (r: GetAnalysisRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.AnalysisRule
          in
          return try await self.inner.getAnalysisRule(request: r, options: o)
        })
    }

    public func listAnalysisRules(
      request: ListAnalysisRulesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListAnalysisRulesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAnalysisRules",
        action: {
          (r: ListAnalysisRulesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListAnalysisRulesResponse
          in
          return try await self.inner.listAnalysisRules(request: r, options: o)
        })
    }

    public func updateAnalysisRule(
      request: UpdateAnalysisRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.AnalysisRule {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAnalysisRule",
        action: {
          (r: UpdateAnalysisRuleRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.AnalysisRule
          in
          return try await self.inner.updateAnalysisRule(request: r, options: o)
        })
    }

    public func deleteAnalysisRule(
      request: DeleteAnalysisRuleRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAnalysisRule",
        action: {
          (r: DeleteAnalysisRuleRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteAnalysisRule(request: r, options: o)
        })
    }

    public func getEncryptionSpec(
      request: GetEncryptionSpecRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.EncryptionSpec {
      try await self._intercept(
        request: request,
        options: options,
        name: "getEncryptionSpec",
        action: {
          (r: GetEncryptionSpecRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.EncryptionSpec
          in
          return try await self.inner.getEncryptionSpec(request: r, options: o)
        })
    }

    public func initializeEncryptionSpec(
      request: InitializeEncryptionSpecRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "initializeEncryptionSpec",
        action: {
          (r: InitializeEncryptionSpecRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.initializeEncryptionSpec(request: r, options: o)
        })
    }

    public func createView(
      request: CreateViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.View {
      try await self._intercept(
        request: request,
        options: options,
        name: "createView",
        action: {
          (r: CreateViewRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.View
          in
          return try await self.inner.createView(request: r, options: o)
        })
    }

    public func getView(
      request: GetViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.View {
      try await self._intercept(
        request: request,
        options: options,
        name: "getView",
        action: {
          (r: GetViewRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.View
          in
          return try await self.inner.getView(request: r, options: o)
        })
    }

    public func listViews(
      request: ListViewsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListViewsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listViews",
        action: {
          (r: ListViewsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListViewsResponse
          in
          return try await self.inner.listViews(request: r, options: o)
        })
    }

    public func updateView(
      request: UpdateViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.View {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateView",
        action: {
          (r: UpdateViewRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.View
          in
          return try await self.inner.updateView(request: r, options: o)
        })
    }

    public func deleteView(
      request: DeleteViewRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteView",
        action: { (r: DeleteViewRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteView(request: r, options: o)
        })
    }

    public func queryMetrics(
      request: QueryMetricsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryMetrics",
        action: {
          (r: QueryMetricsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.queryMetrics(request: r, options: o)
        })
    }

    public func createQaQuestion(
      request: CreateQaQuestionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaQuestion {
      try await self._intercept(
        request: request,
        options: options,
        name: "createQaQuestion",
        action: {
          (r: CreateQaQuestionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaQuestion
          in
          return try await self.inner.createQaQuestion(request: r, options: o)
        })
    }

    public func getQaQuestion(
      request: GetQaQuestionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaQuestion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getQaQuestion",
        action: {
          (r: GetQaQuestionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaQuestion
          in
          return try await self.inner.getQaQuestion(request: r, options: o)
        })
    }

    public func updateQaQuestion(
      request: UpdateQaQuestionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaQuestion {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateQaQuestion",
        action: {
          (r: UpdateQaQuestionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaQuestion
          in
          return try await self.inner.updateQaQuestion(request: r, options: o)
        })
    }

    public func deleteQaQuestion(
      request: DeleteQaQuestionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteQaQuestion",
        action: {
          (r: DeleteQaQuestionRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteQaQuestion(request: r, options: o)
        })
    }

    public func listQaQuestions(
      request: ListQaQuestionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListQaQuestionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listQaQuestions",
        action: {
          (r: ListQaQuestionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListQaQuestionsResponse
          in
          return try await self.inner.listQaQuestions(request: r, options: o)
        })
    }

    public func createQaScorecard(
      request: CreateQaScorecardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaScorecard {
      try await self._intercept(
        request: request,
        options: options,
        name: "createQaScorecard",
        action: {
          (r: CreateQaScorecardRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaScorecard
          in
          return try await self.inner.createQaScorecard(request: r, options: o)
        })
    }

    public func getQaScorecard(
      request: GetQaScorecardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaScorecard {
      try await self._intercept(
        request: request,
        options: options,
        name: "getQaScorecard",
        action: {
          (r: GetQaScorecardRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaScorecard
          in
          return try await self.inner.getQaScorecard(request: r, options: o)
        })
    }

    public func updateQaScorecard(
      request: UpdateQaScorecardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaScorecard {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateQaScorecard",
        action: {
          (r: UpdateQaScorecardRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaScorecard
          in
          return try await self.inner.updateQaScorecard(request: r, options: o)
        })
    }

    public func deleteQaScorecard(
      request: DeleteQaScorecardRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteQaScorecard",
        action: {
          (r: DeleteQaScorecardRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteQaScorecard(request: r, options: o)
        })
    }

    public func listQaScorecards(
      request: ListQaScorecardsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListQaScorecardsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listQaScorecards",
        action: {
          (r: ListQaScorecardsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListQaScorecardsResponse
          in
          return try await self.inner.listQaScorecards(request: r, options: o)
        })
    }

    public func createQaScorecardRevision(
      request: CreateQaScorecardRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision {
      try await self._intercept(
        request: request,
        options: options,
        name: "createQaScorecardRevision",
        action: {
          (r: CreateQaScorecardRevisionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision
          in
          return try await self.inner.createQaScorecardRevision(request: r, options: o)
        })
    }

    public func getQaScorecardRevision(
      request: GetQaScorecardRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision {
      try await self._intercept(
        request: request,
        options: options,
        name: "getQaScorecardRevision",
        action: {
          (r: GetQaScorecardRevisionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision
          in
          return try await self.inner.getQaScorecardRevision(request: r, options: o)
        })
    }

    public func tuneQaScorecardRevision(
      request: TuneQaScorecardRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "tuneQaScorecardRevision",
        action: {
          (r: TuneQaScorecardRevisionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.tuneQaScorecardRevision(request: r, options: o)
        })
    }

    public func deployQaScorecardRevision(
      request: DeployQaScorecardRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision {
      try await self._intercept(
        request: request,
        options: options,
        name: "deployQaScorecardRevision",
        action: {
          (r: DeployQaScorecardRevisionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision
          in
          return try await self.inner.deployQaScorecardRevision(request: r, options: o)
        })
    }

    public func undeployQaScorecardRevision(
      request: UndeployQaScorecardRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision {
      try await self._intercept(
        request: request,
        options: options,
        name: "undeployQaScorecardRevision",
        action: {
          (r: UndeployQaScorecardRevisionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.QaScorecardRevision
          in
          return try await self.inner.undeployQaScorecardRevision(request: r, options: o)
        })
    }

    public func deleteQaScorecardRevision(
      request: DeleteQaScorecardRevisionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteQaScorecardRevision",
        action: {
          (r: DeleteQaScorecardRevisionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteQaScorecardRevision(request: r, options: o)
        })
    }

    public func listQaScorecardRevisions(
      request: ListQaScorecardRevisionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListQaScorecardRevisionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listQaScorecardRevisions",
        action: {
          (r: ListQaScorecardRevisionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListQaScorecardRevisionsResponse
          in
          return try await self.inner.listQaScorecardRevisions(request: r, options: o)
        })
    }

    public func createFeedbackLabel(
      request: CreateFeedbackLabelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.FeedbackLabel {
      try await self._intercept(
        request: request,
        options: options,
        name: "createFeedbackLabel",
        action: {
          (r: CreateFeedbackLabelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.FeedbackLabel
          in
          return try await self.inner.createFeedbackLabel(request: r, options: o)
        })
    }

    public func listFeedbackLabels(
      request: ListFeedbackLabelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListFeedbackLabelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFeedbackLabels",
        action: {
          (r: ListFeedbackLabelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListFeedbackLabelsResponse
          in
          return try await self.inner.listFeedbackLabels(request: r, options: o)
        })
    }

    public func getFeedbackLabel(
      request: GetFeedbackLabelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.FeedbackLabel {
      try await self._intercept(
        request: request,
        options: options,
        name: "getFeedbackLabel",
        action: {
          (r: GetFeedbackLabelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.FeedbackLabel
          in
          return try await self.inner.getFeedbackLabel(request: r, options: o)
        })
    }

    public func updateFeedbackLabel(
      request: UpdateFeedbackLabelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.FeedbackLabel {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateFeedbackLabel",
        action: {
          (r: UpdateFeedbackLabelRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.FeedbackLabel
          in
          return try await self.inner.updateFeedbackLabel(request: r, options: o)
        })
    }

    public func deleteFeedbackLabel(
      request: DeleteFeedbackLabelRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteFeedbackLabel",
        action: {
          (r: DeleteFeedbackLabelRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteFeedbackLabel(request: r, options: o)
        })
    }

    public func listAllFeedbackLabels(
      request: ListAllFeedbackLabelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudContactCenterInsightsV1.ListAllFeedbackLabelsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAllFeedbackLabels",
        action: {
          (r: ListAllFeedbackLabelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudContactCenterInsightsV1.ListAllFeedbackLabelsResponse
          in
          return try await self.inner.listAllFeedbackLabels(request: r, options: o)
        })
    }

    public func bulkUploadFeedbackLabels(
      request: BulkUploadFeedbackLabelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "bulkUploadFeedbackLabels",
        action: {
          (r: BulkUploadFeedbackLabelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.bulkUploadFeedbackLabels(request: r, options: o)
        })
    }

    public func bulkDownloadFeedbackLabels(
      request: BulkDownloadFeedbackLabelsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "bulkDownloadFeedbackLabels",
        action: {
          (r: BulkDownloadFeedbackLabelsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.bulkDownloadFeedbackLabels(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
