// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The conversation source, which is a combination of transcript and audio.
public struct ConversationDataSource: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The source of the conversation.
  public var source: OneOf_Source? = nil

  /// Initialize a new instance of `ConversationDataSource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ConversationDataSource().with { $0.gcsSource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsSource = "gcsSource"
    case dialogflowSource = "dialogflowSource"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var source: OneOf_Source? = nil
    let sourceCheckAndSet = {
      if source != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'source'"))
      }
      source = $0
    }
    if let gcsSource = try container.decodeIfPresent(GcsSource?.self, forKey: .gcsSource) {
      try sourceCheckAndSet(.gcsSource(gcsSource))
    }
    if let dialogflowSource = try container.decodeIfPresent(
      DialogflowSource?.self, forKey: .dialogflowSource)
    {
      try sourceCheckAndSet(.dialogflowSource(dialogflowSource))
    }
    self.source = source
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.source {
      switch choice {
      case .gcsSource(let value):
        try container.encode(value, forKey: .gcsSource)
      case .dialogflowSource(let value):
        try container.encode(value, forKey: .dialogflowSource)
      }
    }
  }

  /// The source of the conversation.
  public enum OneOf_Source: Codable, Equatable, Sendable {
    /// A Cloud Storage location specification for the audio and transcript.
    indirect case gcsSource(GcsSource?)
    /// The source when the conversation comes from Dialogflow.
    indirect case dialogflowSource(DialogflowSource?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.ConversationDataSource"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
