// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

/// Enum for the different types of issues a tuning dataset can have.
/// These warnings are currentlyraised when trying to validate a dataset for
/// tuning a scorecard.
public enum DatasetValidationWarning: Codable, Equatable, Sendable {
  /// Unspecified data validation warning.
  case unspecified
  /// A non-trivial percentage of the feedback labels are invalid.
  case tooManyInvalidFeedbackLabels
  /// The quantity of valid feedback labels provided is less than the
  /// recommended minimum.
  case insufficientFeedbackLabels
  /// One or more of the answers have less than the recommended minimum of
  /// feedback labels.
  case insufficientFeedbackLabelsPerAnswer
  /// All the labels in the dataset come from a single answer choice.
  case allFeedbackLabelsHaveTheSameAnswer
  /// Encodes an unknown integer value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownIntValue(Int)
  /// Encodes an unknown string value.
  ///
  /// The most common cause for an unknown values is for the service to send
  /// a value unknown to the library. We recommend you update your library to
  /// the latest version.
  case unknownStringValue(String)

  public init() {
    self = .unspecified
  }

  /// Returns the integer value associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown string value, this returns `nil`.
  public var intValue: Int? {
    switch self {
    case .unspecified: return 0
    case .tooManyInvalidFeedbackLabels: return 1
    case .insufficientFeedbackLabels: return 2
    case .insufficientFeedbackLabelsPerAnswer: return 3
    case .allFeedbackLabelsHaveTheSameAnswer: return 4
    case .unknownIntValue(let v): return v
    case .unknownStringValue: return nil
    }
  }

  /// Returns the string value (or name) associated with the enumeration.
  ///
  /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
  public var stringValue: Swift.String? {
    switch self {
    case .unspecified: return "DATASET_VALIDATION_WARNING_UNSPECIFIED"
    case .tooManyInvalidFeedbackLabels: return "TOO_MANY_INVALID_FEEDBACK_LABELS"
    case .insufficientFeedbackLabels: return "INSUFFICIENT_FEEDBACK_LABELS"
    case .insufficientFeedbackLabelsPerAnswer: return "INSUFFICIENT_FEEDBACK_LABELS_PER_ANSWER"
    case .allFeedbackLabelsHaveTheSameAnswer: return "ALL_FEEDBACK_LABELS_HAVE_THE_SAME_ANSWER"
    case .unknownIntValue: return nil
    case .unknownStringValue(let v): return v
    }
  }

  /// Initialize from a string value.
  ///
  /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DatasetValidationWarning/unknownStringValue(_:)).
  public init(stringValue: Swift.String) {
    switch stringValue {
    case "DATASET_VALIDATION_WARNING_UNSPECIFIED": self = .unspecified
    case "TOO_MANY_INVALID_FEEDBACK_LABELS": self = .tooManyInvalidFeedbackLabels
    case "INSUFFICIENT_FEEDBACK_LABELS": self = .insufficientFeedbackLabels
    case "INSUFFICIENT_FEEDBACK_LABELS_PER_ANSWER": self = .insufficientFeedbackLabelsPerAnswer
    case "ALL_FEEDBACK_LABELS_HAVE_THE_SAME_ANSWER": self = .allFeedbackLabelsHaveTheSameAnswer
    default: self = .unknownStringValue(stringValue)
    }
  }

  /// Initialize from an integer value.
  ///
  /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DatasetValidationWarning/unknownIntValue(_:)).
  public init(intValue: Int) {
    switch intValue {
    case 0: self = .unspecified
    case 1: self = .tooManyInvalidFeedbackLabels
    case 2: self = .insufficientFeedbackLabels
    case 3: self = .insufficientFeedbackLabelsPerAnswer
    case 4: self = .allFeedbackLabelsHaveTheSameAnswer
    default: self = .unknownIntValue(intValue)
    }
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if let v = try? container.decode(Int.self) {
      self.init(intValue: v)
      return
    }
    if let s = try? container.decode(String.self) {
      if let v = Int(s) {
        self.init(intValue: v)
      } else {
        self.init(stringValue: s)
      }
      return
    }
    throw DecodingError.dataCorruptedError(
      in: container, debugDescription: "Expected enum value, must be integer or string.")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .unspecified: return try container.encode(0)
    case .tooManyInvalidFeedbackLabels: return try container.encode(1)
    case .insufficientFeedbackLabels: return try container.encode(2)
    case .insufficientFeedbackLabelsPerAnswer: return try container.encode(3)
    case .allFeedbackLabelsHaveTheSameAnswer: return try container.encode(4)
    case .unknownIntValue(let v): return try container.encode(v)
    case .unknownStringValue(let v): return try container.encode(v)
    }
  }
}
