// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Dialogflow interaction data.
public struct DialogflowInteractionData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The Dialogflow intent resource path. Format:
  /// projects/{project}/agent/{agent}/intents/{intent}
  public var dialogflowIntentId: Swift.String = Swift.String()

  /// The confidence of the match ranging from 0.0 (completely uncertain) to 1.0
  /// (completely certain).
  public var confidence: Swift.Float = Swift.Float()

  /// Initialize a new instance of `DialogflowInteractionData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DialogflowInteractionData().with { $0.dialogflowIntentId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.DialogflowInteractionData"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
