// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Dialogflow interaction data.
public struct DialogflowInteractionData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The Dialogflow intent resource path. Format:
  /// projects/{project}/agent/{agent}/intents/{intent}
  public var dialogflowIntentId: Swift.String = Swift.String()

  /// The confidence of the match ranging from 0.0 (completely uncertain) to 1.0
  /// (completely certain).
  public var confidence: Swift.Float = Swift.Float()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DialogflowInteractionData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DialogflowInteractionData().with { $0.dialogflowIntentId = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let dialogflowIntentId = CodingKeys(stringValue: "dialogflowIntentId")
    static let confidence = CodingKeys(stringValue: "confidence")

    static let _knownKeys: Set<Swift.String> = [
      "dialogflowIntentId",
      "confidence",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dialogflowIntentId) {
      self.dialogflowIntentId = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidence) {
      self.confidence = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dialogflowIntentId, forKey: .dialogflowIntentId)
    try container.encode(self.confidence, forKey: .confidence)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.DialogflowInteractionData"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
