// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A dimension determines the grouping key for the query. In SQL terms, these
/// would be part of both the "SELECT" and "GROUP BY" clauses.
public struct Dimension: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The key of the dimension.
  public var dimensionKey: Dimension.DimensionKey = Dimension.DimensionKey()

  /// Output-only metadata about the dimension.
  public var dimensionMetadata: OneOf_DimensionMetadata? = nil

  /// Initialize a new instance of `Dimension`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Dimension().with { $0.issueDimensionMetadata = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case issueDimensionMetadata = "issueDimensionMetadata"
    case agentDimensionMetadata = "agentDimensionMetadata"
    case qaQuestionDimensionMetadata = "qaQuestionDimensionMetadata"
    case qaQuestionAnswerDimensionMetadata = "qaQuestionAnswerDimensionMetadata"
    case dimensionKey = "dimensionKey"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.dimensionKey = try container.decode(Dimension.DimensionKey.self, forKey: .dimensionKey)

    var dimensionMetadata: OneOf_DimensionMetadata? = nil
    let dimensionMetadataCheckAndSet = {
      if dimensionMetadata != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dimensionMetadata'"))
      }
      dimensionMetadata = $0
    }
    if let issueDimensionMetadata = try container.decodeIfPresent(
      Dimension.IssueDimensionMetadata?.self, forKey: .issueDimensionMetadata)
    {
      try dimensionMetadataCheckAndSet(.issueDimensionMetadata(issueDimensionMetadata))
    }
    if let agentDimensionMetadata = try container.decodeIfPresent(
      Dimension.AgentDimensionMetadata?.self, forKey: .agentDimensionMetadata)
    {
      try dimensionMetadataCheckAndSet(.agentDimensionMetadata(agentDimensionMetadata))
    }
    if let qaQuestionDimensionMetadata = try container.decodeIfPresent(
      Dimension.QaQuestionDimensionMetadata?.self, forKey: .qaQuestionDimensionMetadata)
    {
      try dimensionMetadataCheckAndSet(.qaQuestionDimensionMetadata(qaQuestionDimensionMetadata))
    }
    if let qaQuestionAnswerDimensionMetadata = try container.decodeIfPresent(
      Dimension.QaQuestionAnswerDimensionMetadata?.self, forKey: .qaQuestionAnswerDimensionMetadata)
    {
      try dimensionMetadataCheckAndSet(
        .qaQuestionAnswerDimensionMetadata(qaQuestionAnswerDimensionMetadata))
    }
    self.dimensionMetadata = dimensionMetadata
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.dimensionKey, forKey: .dimensionKey)

    if let choice = self.dimensionMetadata {
      switch choice {
      case .issueDimensionMetadata(let value):
        try container.encode(value, forKey: .issueDimensionMetadata)
      case .agentDimensionMetadata(let value):
        try container.encode(value, forKey: .agentDimensionMetadata)
      case .qaQuestionDimensionMetadata(let value):
        try container.encode(value, forKey: .qaQuestionDimensionMetadata)
      case .qaQuestionAnswerDimensionMetadata(let value):
        try container.encode(value, forKey: .qaQuestionAnswerDimensionMetadata)
      }
    }
  }

  /// Metadata about the issue dimension.
  public struct IssueDimensionMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The issue ID.
    public var issueId: Swift.String = Swift.String()

    /// The issue display name.
    public var issueDisplayName: Swift.String = Swift.String()

    /// The parent issue model ID.
    public var issueModelId: Swift.String = Swift.String()

    /// Initialize a new instance of `IssueDimensionMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IssueDimensionMetadata().with { $0.issueId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.Dimension.IssueDimensionMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Metadata about the agent dimension.
  public struct AgentDimensionMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. A user-specified string representing the agent.
    public var agentId: Swift.String = Swift.String()

    /// Optional. The agent's name
    public var agentDisplayName: Swift.String = Swift.String()

    /// Optional. A user-specified string representing the agent's team.
    public var agentTeam: Swift.String = Swift.String()

    /// Initialize a new instance of `AgentDimensionMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AgentDimensionMetadata().with { $0.agentId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.Dimension.AgentDimensionMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Metadata about the QA question dimension.
  public struct QaQuestionDimensionMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The QA scorecard ID.
    public var qaScorecardId: Swift.String = Swift.String()

    /// Optional. The QA question ID.
    public var qaQuestionId: Swift.String = Swift.String()

    /// Optional. The full body of the question.
    public var questionBody: Swift.String = Swift.String()

    /// Initialize a new instance of `QaQuestionDimensionMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QaQuestionDimensionMetadata().with { $0.qaScorecardId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.Dimension.QaQuestionDimensionMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Metadata about the QA question-answer dimension.
  /// This is useful for showing the answer distribution for questions for a
  /// given scorecard.
  public struct QaQuestionAnswerDimensionMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The QA scorecard ID.
    public var qaScorecardId: Swift.String = Swift.String()

    /// Optional. The QA question ID.
    public var qaQuestionId: Swift.String = Swift.String()

    /// Optional. The full body of the question.
    public var questionBody: Swift.String = Swift.String()

    /// Optional. The full body of the question.
    public var answerValue: Swift.String = Swift.String()

    /// Initialize a new instance of `QaQuestionAnswerDimensionMetadata`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QaQuestionAnswerDimensionMetadata().with { $0.qaScorecardId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.Dimension.QaQuestionAnswerDimensionMetadata"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The key of the dimension.
  public enum DimensionKey: Codable, Equatable, Sendable {
    /// The key of the dimension is unspecified.
    case unspecified
    /// The dimension is keyed by issues.
    case issue
    /// The dimension is keyed by agents.
    case agent
    /// The dimension is keyed by agent teams.
    case agentTeam
    /// The dimension is keyed by QaQuestionIds.
    /// Note that: We only group by the QuestionId and not the revision-id of the
    /// scorecard this question is a part of. This allows for showing stats for
    /// the same question across different scorecard revisions.
    case qaQuestionId
    /// The dimension is keyed by QaQuestionIds-Answer value pairs.
    /// Note that: We only group by the QuestionId and not the revision-id of the
    /// scorecard this question is a part of. This allows for showing
    /// distribution of answers per question across different scorecard
    /// revisions.
    case qaQuestionAnswerValue
    /// The dimension is keyed by the conversation profile ID.
    case conversationProfileId
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .issue: return 1
      case .agent: return 2
      case .agentTeam: return 3
      case .qaQuestionId: return 4
      case .qaQuestionAnswerValue: return 5
      case .conversationProfileId: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DIMENSION_KEY_UNSPECIFIED"
      case .issue: return "ISSUE"
      case .agent: return "AGENT"
      case .agentTeam: return "AGENT_TEAM"
      case .qaQuestionId: return "QA_QUESTION_ID"
      case .qaQuestionAnswerValue: return "QA_QUESTION_ANSWER_VALUE"
      case .conversationProfileId: return "CONVERSATION_PROFILE_ID"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DimensionKey/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DIMENSION_KEY_UNSPECIFIED": self = .unspecified
      case "ISSUE": self = .issue
      case "AGENT": self = .agent
      case "AGENT_TEAM": self = .agentTeam
      case "QA_QUESTION_ID": self = .qaQuestionId
      case "QA_QUESTION_ANSWER_VALUE": self = .qaQuestionAnswerValue
      case "CONVERSATION_PROFILE_ID": self = .conversationProfileId
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DimensionKey/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .issue
      case 2: self = .agent
      case 3: self = .agentTeam
      case 4: self = .qaQuestionId
      case 5: self = .qaQuestionAnswerValue
      case 6: self = .conversationProfileId
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .issue: return try container.encode(1)
      case .agent: return try container.encode(2)
      case .agentTeam: return try container.encode(3)
      case .qaQuestionId: return try container.encode(4)
      case .qaQuestionAnswerValue: return try container.encode(5)
      case .conversationProfileId: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Output-only metadata about the dimension.
  public enum OneOf_DimensionMetadata: Codable, Equatable, Sendable {
    /// Output only. Metadata about the issue dimension.
    indirect case issueDimensionMetadata(Dimension.IssueDimensionMetadata?)
    /// Output only. Metadata about the agent dimension.
    indirect case agentDimensionMetadata(Dimension.AgentDimensionMetadata?)
    /// Output only. Metadata about the QA question dimension.
    indirect case qaQuestionDimensionMetadata(Dimension.QaQuestionDimensionMetadata?)
    /// Output only. Metadata about the QA question-answer dimension.
    indirect case qaQuestionAnswerDimensionMetadata(Dimension.QaQuestionAnswerDimensionMetadata?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.Dimension"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
