// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request to export insights.
public struct ExportInsightsDataRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource to export data from.
  public var parent: Swift.String = Swift.String()

  /// A filter to reduce results to a specific subset. Useful for exporting
  /// conversations with specific properties.
  public var filter: Swift.String = Swift.String()

  /// A fully qualified KMS key name for BigQuery tables protected by CMEK.
  /// Format:
  /// projects/{project}/locations/{location}/keyRings/{keyring}/cryptoKeys/{key}/cryptoKeyVersions/{version}
  public var kmsKey: Swift.String = Swift.String()

  /// Options for what to do if the destination table already exists.
  public var writeDisposition: ExportInsightsDataRequest.WriteDisposition =
    ExportInsightsDataRequest.WriteDisposition()

  /// Exporter destination.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `ExportInsightsDataRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportInsightsDataRequest().with { $0.bigQueryDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case bigQueryDestination = "bigQueryDestination"
    case parent = "parent"
    case filter = "filter"
    case kmsKey = "kmsKey"
    case writeDisposition = "writeDisposition"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.filter = try container.decode(Swift.String.self, forKey: .filter)
    self.kmsKey = try container.decode(Swift.String.self, forKey: .kmsKey)
    self.writeDisposition = try container.decode(
      ExportInsightsDataRequest.WriteDisposition.self, forKey: .writeDisposition)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let bigQueryDestination = try container.decodeIfPresent(
      ExportInsightsDataRequest.BigQueryDestination?.self, forKey: .bigQueryDestination)
    {
      try destinationCheckAndSet(.bigQueryDestination(bigQueryDestination))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.filter, forKey: .filter)
    try container.encode(self.kmsKey, forKey: .kmsKey)
    try container.encode(self.writeDisposition, forKey: .writeDisposition)

    if let choice = self.destination {
      switch choice {
      case .bigQueryDestination(let value):
        try container.encode(value, forKey: .bigQueryDestination)
      }
    }
  }

  /// A BigQuery Table Reference.
  public struct BigQueryDestination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// A project ID or number. If specified, then export will attempt to
    /// write data to this project instead of the resource project. Otherwise,
    /// the resource project will be used.
    public var projectId: Swift.String = Swift.String()

    /// Required. The name of the BigQuery dataset that the snapshot result
    /// should be exported to. If this dataset does not exist, the export call
    /// returns an INVALID_ARGUMENT error.
    public var dataset: Swift.String = Swift.String()

    /// The BigQuery table name to which the insights data should be written.
    /// If this table does not exist, the export call returns an INVALID_ARGUMENT
    /// error.
    public var table: Swift.String = Swift.String()

    /// Initialize a new instance of `BigQueryDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BigQueryDestination().with { $0.projectId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.ExportInsightsDataRequest.BigQueryDestination"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Specifies the action that occurs if the destination table already exists.
  public enum WriteDisposition: Codable, Equatable, Sendable {
    /// Write disposition is not specified. Defaults to WRITE_TRUNCATE.
    case unspecified
    /// If the table already exists, BigQuery will overwrite the table data and
    /// use the schema from the load.
    case writeTruncate
    /// If the table already exists, BigQuery will append data to the table.
    case writeAppend
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .writeTruncate: return 1
      case .writeAppend: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "WRITE_DISPOSITION_UNSPECIFIED"
      case .writeTruncate: return "WRITE_TRUNCATE"
      case .writeAppend: return "WRITE_APPEND"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:WriteDisposition/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "WRITE_DISPOSITION_UNSPECIFIED": self = .unspecified
      case "WRITE_TRUNCATE": self = .writeTruncate
      case "WRITE_APPEND": self = .writeAppend
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:WriteDisposition/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .writeTruncate
      case 2: self = .writeAppend
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .writeTruncate: return try container.encode(1)
      case .writeAppend: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Exporter destination.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Specified if sink is a BigQuery table.
    indirect case bigQueryDestination(ExportInsightsDataRequest.BigQueryDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.ExportInsightsDataRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
