// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Agent Assist frequently-asked-question answer data.
public struct FaqAnswerData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The piece of text from the `source` knowledge base document.
  public var answer: Swift.String = Swift.String()

  /// The system's confidence score that this answer is a good match for this
  /// conversation, ranging from 0.0 (completely uncertain) to 1.0 (completely
  /// certain).
  public var confidenceScore: Swift.Float = Swift.Float()

  /// The corresponding FAQ question.
  public var question: Swift.String = Swift.String()

  /// Map that contains metadata about the FAQ answer and the document that
  /// it originates from.
  public var metadata: [Swift.String: Swift.String] = [:]

  /// The name of the answer record.
  /// Format:
  /// projects/{project}/locations/{location}/answerRecords/{answer_record}
  public var queryRecord: Swift.String = Swift.String()

  /// The knowledge document that this answer was extracted from.
  /// Format:
  /// projects/{project}/knowledgeBases/{knowledge_base}/documents/{document}.
  public var source: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `FaqAnswerData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FaqAnswerData().with { $0.answer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let answer = CodingKeys(stringValue: "answer")
    static let confidenceScore = CodingKeys(stringValue: "confidenceScore")
    static let question = CodingKeys(stringValue: "question")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let queryRecord = CodingKeys(stringValue: "queryRecord")
    static let source = CodingKeys(stringValue: "source")

    static let _knownKeys: Set<Swift.String> = [
      "answer",
      "confidenceScore",
      "question",
      "metadata",
      "queryRecord",
      "source",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .answer) {
      self.answer = value
    }
    if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidenceScore) {
      self.confidenceScore = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .question) {
      self.question = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .metadata)
    {
      self.metadata = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .queryRecord) {
      self.queryRecord = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .source) {
      self.source = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.answer, forKey: .answer)
    try container.encode(self.confidenceScore, forKey: .confidenceScore)
    try container.encode(self.question, forKey: .question)
    try container.encode(self.metadata, forKey: .metadata)
    try container.encode(self.queryRecord, forKey: .queryRecord)
    try container.encode(self.source, forKey: .source)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.FaqAnswerData"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
