// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Agent Assist frequently-asked-question answer data.
public struct FaqAnswerData: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The piece of text from the `source` knowledge base document.
  public var answer: Swift.String = Swift.String()

  /// The system's confidence score that this answer is a good match for this
  /// conversation, ranging from 0.0 (completely uncertain) to 1.0 (completely
  /// certain).
  public var confidenceScore: Swift.Float = Swift.Float()

  /// The corresponding FAQ question.
  public var question: Swift.String = Swift.String()

  /// Map that contains metadata about the FAQ answer and the document that
  /// it originates from.
  public var metadata: [Swift.String: Swift.String] = [:]

  /// The name of the answer record.
  /// Format:
  /// projects/{project}/locations/{location}/answerRecords/{answer_record}
  public var queryRecord: Swift.String = Swift.String()

  /// The knowledge document that this answer was extracted from.
  /// Format:
  /// projects/{project}/knowledgeBases/{knowledge_base}/documents/{document}.
  public var source: Swift.String = Swift.String()

  /// Initialize a new instance of `FaqAnswerData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = FaqAnswerData().with { $0.answer = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.FaqAnswerData"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
