// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Request to list conversations.
public struct ListConversationsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The parent resource of the conversation.
  public var parent: Swift.String = Swift.String()

  /// The maximum number of conversations to return in the response. A valid page
  /// size ranges from 0 to 100,000 inclusive. If the page size is zero or
  /// unspecified, a default page size of 100 will be chosen. Note that a call
  /// might return fewer results than the requested page size.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// The value returned by the last `ListConversationsResponse`. This value
  /// indicates that this is a continuation of a prior `ListConversations` call
  /// and that the system should return the next page of data.
  public var pageToken: Swift.String = Swift.String()

  /// A filter to reduce results to a specific subset. Useful for querying
  /// conversations with specific properties.
  public var filter: Swift.String = Swift.String()

  /// Optional. The attribute by which to order conversations in the response.
  /// If empty, conversations will be ordered by descending creation time.
  /// Supported values are one of the following:
  ///
  /// * create_time
  /// * customer_satisfaction_rating
  /// * duration
  /// * latest_analysis
  /// * start_time
  /// * turn_count
  ///
  /// The default sort order is ascending. To specify order, append `asc` or
  /// `desc` (`create_time desc`).
  /// For more details, see [Google AIPs
  /// Ordering](https://google.aip.dev/132#ordering).
  public var orderBy: Swift.String = Swift.String()

  /// The level of details of the conversation. Default is `BASIC`.
  public var view: ConversationView = ConversationView()

  /// Initialize a new instance of `ListConversationsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListConversationsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.ListConversationsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
