// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Configuration information of a phrase match rule.
public struct PhraseMatchRuleConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The configuration of the phrase match rule.
  public var config: OneOf_Config? = nil

  /// Initialize a new instance of `PhraseMatchRuleConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PhraseMatchRuleConfig().with { $0.exactMatchConfig = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case exactMatchConfig = "exactMatchConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var config: OneOf_Config? = nil
    let configCheckAndSet = {
      if config != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'config'"))
      }
      config = $0
    }
    if let exactMatchConfig = try container.decodeIfPresent(
      ExactMatchConfig?.self, forKey: .exactMatchConfig)
    {
      try configCheckAndSet(.exactMatchConfig(exactMatchConfig))
    }
    self.config = config
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.config {
      switch choice {
      case .exactMatchConfig(let value):
        try container.encode(value, forKey: .exactMatchConfig)
      }
    }
  }

  /// The configuration of the phrase match rule.
  public enum OneOf_Config: Codable, Equatable, Sendable {
    /// The configuration for the exact match rule.
    indirect case exactMatchConfig(ExactMatchConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.PhraseMatchRuleConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
