// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A revision of a QaScorecard.
///
/// Modifying published scorecard fields would invalidate existing scorecard
/// results — the questions may have changed, or the score weighting will make
/// existing scores impossible to understand. So changes must create a new
/// revision, rather than modifying the existing resource.
public struct QaScorecardRevision: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Identifier. The name of the scorecard revision.
  /// Format:
  /// projects/{project}/locations/{location}/qaScorecards/{qa_scorecard}/revisions/{revision}
  public var name: Swift.String = Swift.String()

  /// The snapshot of the scorecard at the time of this revision's creation.
  public var snapshot: QaScorecard? = nil

  /// Output only. The timestamp that the revision was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. Alternative IDs for this revision of the scorecard, e.g.,
  /// `latest`.
  public var alternateIds: [Swift.String] = []

  /// Output only. State of the scorecard revision, indicating whether it's ready
  /// to be used in analysis.
  public var state: QaScorecardRevision.State = QaScorecardRevision.State()

  /// Initialize a new instance of `QaScorecardRevision`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QaScorecardRevision().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Enum representing the set of states a scorecard revision may be in.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified.
    case unspecified
    /// Scorecard model training is in progress.
    case training
    /// Scorecard is being deleted.
    case deleting
    /// Scorecard revision model training failed.
    case trainingFailed
    /// The revision can be used in analysis.
    case ready
    /// The scorecard revision can be edited.
    case editable
    /// Scorecard model training was explicitly cancelled by the user.
    case trainingCancelled
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .training: return 2
      case .deleting: return 7
      case .trainingFailed: return 9
      case .ready: return 11
      case .editable: return 12
      case .trainingCancelled: return 14
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .training: return "TRAINING"
      case .deleting: return "DELETING"
      case .trainingFailed: return "TRAINING_FAILED"
      case .ready: return "READY"
      case .editable: return "EDITABLE"
      case .trainingCancelled: return "TRAINING_CANCELLED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "EDITABLE": self = .editable
      case "TRAINING": self = .training
      case "TRAINING_FAILED": self = .trainingFailed
      case "READY": self = .ready
      case "DELETING": self = .deleting
      case "TRAINING_CANCELLED": self = .trainingCancelled
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 2: self = .training
      case 7: self = .deleting
      case 9: self = .trainingFailed
      case 11: self = .ready
      case 12: self = .editable
      case 14: self = .trainingCancelled
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .training: return try container.encode(2)
      case .deleting: return try container.encode(7)
      case .trainingFailed: return try container.encode(9)
      case .ready: return try container.encode(11)
      case .editable: return try container.encode(12)
      case .trainingCancelled: return try container.encode(14)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.QaScorecardRevision"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
