// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The results of scoring a single conversation against a QaScorecard. Contains
/// a collection of QaAnswers and aggregate score.
public struct QaScorecardResult: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The name of the scorecard result.
  /// Format:
  /// projects/{project}/locations/{location}/qaScorecardResults/{qa_scorecard_result}
  public var name: Swift.String = Swift.String()

  /// The QaScorecardRevision scored by this result.
  public var qaScorecardRevision: Swift.String = Swift.String()

  /// The conversation scored by this result.
  public var conversation: Swift.String = Swift.String()

  /// Output only. The timestamp that the revision was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// ID of the agent that handled the conversation.
  public var agentId: Swift.String = Swift.String()

  /// Set of QaAnswers represented in the result.
  public var qaAnswers: [QaAnswer] = []

  /// The overall numerical score of the result, incorporating any manual edits
  /// if they exist.
  public var score: Swift.Double? = nil

  /// The maximum potential overall score of the scorecard. Any questions
  /// answered using `na_value` are excluded from this calculation.
  public var potentialScore: Swift.Double? = nil

  /// The normalized score, which is the score divided by the potential score.
  /// Any manual edits are included if they exist.
  public var normalizedScore: Swift.Double? = nil

  /// Collection of tags and their scores.
  public var qaTagResults: [QaScorecardResult.QaTagResult] = []

  /// List of all individual score sets.
  public var scoreSources: [QaScorecardResult.ScoreSource] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QaScorecardResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QaScorecardResult().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let qaScorecardRevision = CodingKeys(stringValue: "qaScorecardRevision")
    static let conversation = CodingKeys(stringValue: "conversation")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let agentId = CodingKeys(stringValue: "agentId")
    static let qaAnswers = CodingKeys(stringValue: "qaAnswers")
    static let score = CodingKeys(stringValue: "score")
    static let potentialScore = CodingKeys(stringValue: "potentialScore")
    static let normalizedScore = CodingKeys(stringValue: "normalizedScore")
    static let qaTagResults = CodingKeys(stringValue: "qaTagResults")
    static let scoreSources = CodingKeys(stringValue: "scoreSources")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "qaScorecardRevision",
      "conversation",
      "createTime",
      "agentId",
      "qaAnswers",
      "score",
      "potentialScore",
      "normalizedScore",
      "qaTagResults",
      "scoreSources",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .qaScorecardRevision) {
      self.qaScorecardRevision = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .conversation) {
      self.conversation = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .agentId) {
      self.agentId = value
    }
    if let value = try container.decodeIfPresent([QaAnswer].self, forKey: .qaAnswers) {
      self.qaAnswers = value
    }
    self.score = try container.decodeIfPresent(Swift.Double.self, forKey: .score)
    self.potentialScore = try container.decodeIfPresent(Swift.Double.self, forKey: .potentialScore)
    self.normalizedScore = try container.decodeIfPresent(
      Swift.Double.self, forKey: .normalizedScore)
    if let value = try container.decodeIfPresent(
      [QaScorecardResult.QaTagResult].self, forKey: .qaTagResults)
    {
      self.qaTagResults = value
    }
    if let value = try container.decodeIfPresent(
      [QaScorecardResult.ScoreSource].self, forKey: .scoreSources)
    {
      self.scoreSources = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.qaScorecardRevision, forKey: .qaScorecardRevision)
    try container.encode(self.conversation, forKey: .conversation)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.agentId, forKey: .agentId)
    try container.encode(self.qaAnswers, forKey: .qaAnswers)
    try container.encodeIfPresent(self.score, forKey: .score)
    try container.encodeIfPresent(self.potentialScore, forKey: .potentialScore)
    try container.encodeIfPresent(self.normalizedScore, forKey: .normalizedScore)
    try container.encode(self.qaTagResults, forKey: .qaTagResults)
    try container.encode(self.scoreSources, forKey: .scoreSources)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Tags and their corresponding results.
  public struct QaTagResult: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The tag the score applies to.
    public var tag: Swift.String = Swift.String()

    /// The score the tag applies to.
    public var score: Swift.Double? = nil

    /// The potential score the tag applies to.
    public var potentialScore: Swift.Double? = nil

    /// The normalized score the tag applies to.
    public var normalizedScore: Swift.Double? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QaTagResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QaTagResult().with { $0.tag = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let tag = CodingKeys(stringValue: "tag")
      static let score = CodingKeys(stringValue: "score")
      static let potentialScore = CodingKeys(stringValue: "potentialScore")
      static let normalizedScore = CodingKeys(stringValue: "normalizedScore")

      static let _knownKeys: Set<Swift.String> = [
        "tag",
        "score",
        "potentialScore",
        "normalizedScore",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tag) {
        self.tag = value
      }
      self.score = try container.decodeIfPresent(Swift.Double.self, forKey: .score)
      self.potentialScore = try container.decodeIfPresent(
        Swift.Double.self, forKey: .potentialScore)
      self.normalizedScore = try container.decodeIfPresent(
        Swift.Double.self, forKey: .normalizedScore)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.tag, forKey: .tag)
      try container.encodeIfPresent(self.score, forKey: .score)
      try container.encodeIfPresent(self.potentialScore, forKey: .potentialScore)
      try container.encodeIfPresent(self.normalizedScore, forKey: .normalizedScore)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.QaScorecardResult.QaTagResult"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A scorecard result may have multiple sets of scores from varying sources,
  /// one of which becomes the "main" answer above. A ScoreSource represents
  /// each individual set of scores.
  public struct ScoreSource: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// What created the score.
    public var sourceType: QaScorecardResult.ScoreSource.SourceType = QaScorecardResult.ScoreSource
      .SourceType()

    /// The overall numerical score of the result.
    public var score: Swift.Double? = nil

    /// The maximum potential overall score of the scorecard. Any questions
    /// answered using `na_value` are excluded from this calculation.
    public var potentialScore: Swift.Double? = nil

    /// The normalized score, which is the score divided by the potential score.
    public var normalizedScore: Swift.Double? = nil

    /// Collection of tags and their scores.
    public var qaTagResults: [QaScorecardResult.QaTagResult] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ScoreSource`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ScoreSource().with { $0.sourceType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let sourceType = CodingKeys(stringValue: "sourceType")
      static let score = CodingKeys(stringValue: "score")
      static let potentialScore = CodingKeys(stringValue: "potentialScore")
      static let normalizedScore = CodingKeys(stringValue: "normalizedScore")
      static let qaTagResults = CodingKeys(stringValue: "qaTagResults")

      static let _knownKeys: Set<Swift.String> = [
        "sourceType",
        "score",
        "potentialScore",
        "normalizedScore",
        "qaTagResults",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        QaScorecardResult.ScoreSource.SourceType.self, forKey: .sourceType)
      {
        self.sourceType = value
      }
      self.score = try container.decodeIfPresent(Swift.Double.self, forKey: .score)
      self.potentialScore = try container.decodeIfPresent(
        Swift.Double.self, forKey: .potentialScore)
      self.normalizedScore = try container.decodeIfPresent(
        Swift.Double.self, forKey: .normalizedScore)
      if let value = try container.decodeIfPresent(
        [QaScorecardResult.QaTagResult].self, forKey: .qaTagResults)
      {
        self.qaTagResults = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.sourceType, forKey: .sourceType)
      try container.encodeIfPresent(self.score, forKey: .score)
      try container.encodeIfPresent(self.potentialScore, forKey: .potentialScore)
      try container.encodeIfPresent(self.normalizedScore, forKey: .normalizedScore)
      try container.encode(self.qaTagResults, forKey: .qaTagResults)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// What created the score.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SourceType: Codable, Equatable, Sendable {
      /// Source type is unspecified.
      case unspecified
      /// Score is derived only from system-generated answers.
      case systemGeneratedOnly
      /// Score is derived from both system-generated answers, and includes
      /// any manual edits if they exist.
      case includesManualEdits
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .systemGeneratedOnly: return 1
        case .includesManualEdits: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SOURCE_TYPE_UNSPECIFIED"
        case .systemGeneratedOnly: return "SYSTEM_GENERATED_ONLY"
        case .includesManualEdits: return "INCLUDES_MANUAL_EDITS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SourceType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SOURCE_TYPE_UNSPECIFIED": self = .unspecified
        case "SYSTEM_GENERATED_ONLY": self = .systemGeneratedOnly
        case "INCLUDES_MANUAL_EDITS": self = .includesManualEdits
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SourceType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .systemGeneratedOnly
        case 2: self = .includesManualEdits
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SOURCE_TYPE_UNSPECIFIED")
        case .systemGeneratedOnly: return try container.encode("SYSTEM_GENERATED_ONLY")
        case .includesManualEdits: return try container.encode("INCLUDES_MANUAL_EDITS")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.QaScorecardResult.ScoreSource"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.QaScorecardResult"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
