// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request for querying metrics.
public struct QueryMetricsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The location of the data.
  /// "projects/{project}/locations/{location}"
  public var location: Swift.String = Swift.String()

  /// Required. Filter to select a subset of conversations to compute the
  /// metrics. Must specify a window of the conversation create time to compute
  /// the metrics. The returned metrics will be from the range [DATE(starting
  /// create time), DATE(ending create time)).
  ///
  public var filter: Swift.String = Swift.String()

  /// The time granularity of each data point in the time series.
  /// Defaults to NONE if this field is unspecified.
  public var timeGranularity: QueryMetricsRequest.TimeGranularity =
    QueryMetricsRequest.TimeGranularity()

  /// The dimensions that determine the grouping key for the query. Defaults to
  /// no dimension if this field is unspecified. If a dimension is specified,
  /// its key must also be specified. Each dimension's key must be unique.
  ///
  /// If a time granularity is also specified, metric values in the dimension
  /// will be bucketed by this granularity.
  ///
  /// Up to one dimension is supported for now.
  public var dimensions: [Dimension] = []

  /// Measures to return. Defaults to all measures if this field is unspecified.
  /// A valid mask should traverse from the `measure` field from the response.
  /// For example, a path from a measure mask to get the conversation count is
  /// "conversation_measure.count".
  public var measureMask: GoogleCloudWkt.FieldMask? = nil

  /// Initialize a new instance of `QueryMetricsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryMetricsRequest().with { $0.location = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// A time granularity divides the time line into discrete time periods.
  /// This is useful for defining buckets over which filtering and aggregation
  /// should be performed.
  public enum TimeGranularity: Codable, Equatable, Sendable {
    /// The time granularity is unspecified and will default to NONE.
    case unspecified
    /// No time granularity. The response won't contain a time series.
    /// This is the default value if no time granularity is specified.
    case `none`
    /// Data points in the time series will aggregate at a daily granularity.
    /// 1 day means [midnight to midnight).
    case daily
    /// Data points in the time series will aggregate at a daily granularity.
    /// 1 HOUR means [01:00 to 02:00).
    case hourly
    /// Data points in the time series will aggregate at a daily granularity.
    /// PER_MINUTE means [01:00 to 01:01).
    case perMinute
    /// Data points in the time series will aggregate at a 1 minute  granularity.
    /// PER_5_MINUTES means [01:00 to 01:05).
    case per5Minutes
    /// Data points in the time series will aggregate at a monthly granularity.
    /// 1 MONTH means [01st of the month to 1st of the next month).
    case monthly
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .daily: return 2
      case .hourly: return 3
      case .perMinute: return 4
      case .per5Minutes: return 5
      case .monthly: return 6
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TIME_GRANULARITY_UNSPECIFIED"
      case .`none`: return "NONE"
      case .daily: return "DAILY"
      case .hourly: return "HOURLY"
      case .perMinute: return "PER_MINUTE"
      case .per5Minutes: return "PER_5_MINUTES"
      case .monthly: return "MONTHLY"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:TimeGranularity/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TIME_GRANULARITY_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "DAILY": self = .daily
      case "HOURLY": self = .hourly
      case "PER_MINUTE": self = .perMinute
      case "PER_5_MINUTES": self = .per5Minutes
      case "MONTHLY": self = .monthly
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:TimeGranularity/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .daily
      case 3: self = .hourly
      case 4: self = .perMinute
      case 5: self = .per5Minutes
      case 6: self = .monthly
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`none`: return try container.encode(1)
      case .daily: return try container.encode(2)
      case .hourly: return try container.encode(3)
      case .perMinute: return try container.encode(4)
      case .per5Minutes: return try container.encode(5)
      case .monthly: return try container.encode(6)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.QueryMetricsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
