// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An annotation that was generated during the customer and agent interaction.
public struct RuntimeAnnotation: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The unique identifier of the annotation.
  /// Format:
  /// projects/{project}/locations/{location}/conversationDatasets/{dataset}/conversationDataItems/{data_item}/conversationAnnotations/{annotation}
  public var annotationId: Swift.String = Swift.String()

  /// The time at which this annotation was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// The boundary in the conversation where the annotation starts, inclusive.
  public var startBoundary: AnnotationBoundary? = nil

  /// The boundary in the conversation where the annotation ends, inclusive.
  public var endBoundary: AnnotationBoundary? = nil

  /// The feedback that the customer has about the answer in `data`.
  public var answerFeedback: AnswerFeedback? = nil

  /// Explicit input used for generating the answer
  public var userInput: RuntimeAnnotation.UserInput? = nil

  /// The data in the annotation.
  public var data: OneOf_Data? = nil

  /// Initialize a new instance of `RuntimeAnnotation`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RuntimeAnnotation().with { $0.articleSuggestion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case articleSuggestion = "articleSuggestion"
    case faqAnswer = "faqAnswer"
    case smartReply = "smartReply"
    case smartComposeSuggestion = "smartComposeSuggestion"
    case dialogflowInteraction = "dialogflowInteraction"
    case conversationSummarizationSuggestion = "conversationSummarizationSuggestion"
    case annotationId = "annotationId"
    case createTime = "createTime"
    case startBoundary = "startBoundary"
    case endBoundary = "endBoundary"
    case answerFeedback = "answerFeedback"
    case userInput = "userInput"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.annotationId = try container.decode(Swift.String.self, forKey: .annotationId)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.startBoundary = try container.decodeIfPresent(
      AnnotationBoundary.self, forKey: .startBoundary)
    self.endBoundary = try container.decodeIfPresent(AnnotationBoundary.self, forKey: .endBoundary)
    self.answerFeedback = try container.decodeIfPresent(
      AnswerFeedback.self, forKey: .answerFeedback)
    self.userInput = try container.decodeIfPresent(
      RuntimeAnnotation.UserInput.self, forKey: .userInput)

    var data: OneOf_Data? = nil
    let dataCheckAndSet = {
      if data != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'data'"
          ))
      }
      data = $0
    }
    if let articleSuggestion = try container.decodeIfPresent(
      ArticleSuggestionData?.self, forKey: .articleSuggestion)
    {
      try dataCheckAndSet(.articleSuggestion(articleSuggestion))
    }
    if let faqAnswer = try container.decodeIfPresent(FaqAnswerData?.self, forKey: .faqAnswer) {
      try dataCheckAndSet(.faqAnswer(faqAnswer))
    }
    if let smartReply = try container.decodeIfPresent(SmartReplyData?.self, forKey: .smartReply) {
      try dataCheckAndSet(.smartReply(smartReply))
    }
    if let smartComposeSuggestion = try container.decodeIfPresent(
      SmartComposeSuggestionData?.self, forKey: .smartComposeSuggestion)
    {
      try dataCheckAndSet(.smartComposeSuggestion(smartComposeSuggestion))
    }
    if let dialogflowInteraction = try container.decodeIfPresent(
      DialogflowInteractionData?.self, forKey: .dialogflowInteraction)
    {
      try dataCheckAndSet(.dialogflowInteraction(dialogflowInteraction))
    }
    if let conversationSummarizationSuggestion = try container.decodeIfPresent(
      ConversationSummarizationSuggestionData?.self, forKey: .conversationSummarizationSuggestion)
    {
      try dataCheckAndSet(.conversationSummarizationSuggestion(conversationSummarizationSuggestion))
    }
    self.data = data
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.annotationId, forKey: .annotationId)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.startBoundary, forKey: .startBoundary)
    try container.encode(self.endBoundary, forKey: .endBoundary)
    try container.encode(self.answerFeedback, forKey: .answerFeedback)
    try container.encode(self.userInput, forKey: .userInput)

    if let choice = self.data {
      switch choice {
      case .articleSuggestion(let value):
        try container.encode(value, forKey: .articleSuggestion)
      case .faqAnswer(let value):
        try container.encode(value, forKey: .faqAnswer)
      case .smartReply(let value):
        try container.encode(value, forKey: .smartReply)
      case .smartComposeSuggestion(let value):
        try container.encode(value, forKey: .smartComposeSuggestion)
      case .dialogflowInteraction(let value):
        try container.encode(value, forKey: .dialogflowInteraction)
      case .conversationSummarizationSuggestion(let value):
        try container.encode(value, forKey: .conversationSummarizationSuggestion)
      }
    }
  }

  /// Explicit input used for generating the answer
  public struct UserInput: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Query text. Article Search uses this to store the input query used
    /// to generate the search results.
    public var query: Swift.String = Swift.String()

    /// The resource name of associated generator. Format:
    /// `projects/<Project ID>/locations/<Location ID>/generators/<Generator ID>`
    public var generatorName: Swift.String = Swift.String()

    /// Query source for the answer.
    public var querySource: RuntimeAnnotation.UserInput.QuerySource = RuntimeAnnotation.UserInput
      .QuerySource()

    /// Initialize a new instance of `UserInput`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserInput().with { $0.query = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The source of the query.
    public enum QuerySource: Codable, Equatable, Sendable {
      /// Unknown query source.
      case unspecified
      /// The query is from agents.
      case agentQuery
      /// The query is a query from previous suggestions, e.g. from a preceding
      /// SuggestKnowledgeAssist response.
      case suggestedQuery
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .agentQuery: return 1
        case .suggestedQuery: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "QUERY_SOURCE_UNSPECIFIED"
        case .agentQuery: return "AGENT_QUERY"
        case .suggestedQuery: return "SUGGESTED_QUERY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:QuerySource/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "QUERY_SOURCE_UNSPECIFIED": self = .unspecified
        case "AGENT_QUERY": self = .agentQuery
        case "SUGGESTED_QUERY": self = .suggestedQuery
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:QuerySource/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .agentQuery
        case 2: self = .suggestedQuery
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .agentQuery: return try container.encode(1)
        case .suggestedQuery: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.contactcenterinsights.v1.RuntimeAnnotation.UserInput"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The data in the annotation.
  public enum OneOf_Data: Codable, Equatable, Sendable {
    /// Agent Assist Article Suggestion data.
    indirect case articleSuggestion(ArticleSuggestionData?)
    /// Agent Assist FAQ answer data.
    indirect case faqAnswer(FaqAnswerData?)
    /// Agent Assist Smart Reply data.
    indirect case smartReply(SmartReplyData?)
    /// Agent Assist Smart Compose suggestion data.
    indirect case smartComposeSuggestion(SmartComposeSuggestionData?)
    /// Dialogflow interaction data.
    indirect case dialogflowInteraction(DialogflowInteractionData?)
    /// Conversation summarization suggestion data.
    indirect case conversationSummarizationSuggestion(ConversationSummarizationSuggestionData?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.RuntimeAnnotation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
