// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The CCAI Insights project wide settings.
/// Use these settings to configure the behavior of Insights.
/// View these settings with
/// [`getsettings`](https://cloud.google.com/contact-center/insights/docs/reference/rest/v1/projects.locations/getSettings)
/// and change the settings with
/// [`updateSettings`](https://cloud.google.com/contact-center/insights/docs/reference/rest/v1/projects.locations/updateSettings).
public struct Settings: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the settings resource.
  /// Format:
  /// projects/{project}/locations/{location}/settings
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which the settings was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time at which the settings were last updated.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// A language code to be applied to each transcript segment unless the segment
  /// already specifies a language code. Language code defaults to "en-US" if it
  /// is neither specified on the segment nor here.
  public var languageCode: Swift.String = Swift.String()

  /// The default TTL for newly-created conversations. If a conversation has a
  /// specified expiration, that value will be used instead. Changing this
  /// value will not change the expiration of existing conversations.
  /// Conversations with no expire time persist until they are deleted.
  public var conversationTtl: GoogleCloudWkt.Duration? = nil

  /// A map that maps a notification trigger to a Pub/Sub topic. Each time a
  /// specified trigger occurs, Insights will notify the corresponding Pub/Sub
  /// topic.
  ///
  /// Keys are notification triggers. Supported keys are:
  ///
  /// * "all-triggers": Notify each time any of the supported triggers occurs.
  /// * "create-analysis": Notify each time an analysis is created.
  /// * "create-conversation": Notify each time a conversation is created.
  /// * "export-insights-data": Notify each time an export is complete.
  /// * "ingest-conversations": Notify each time an IngestConversations LRO is
  /// complete.
  /// * "update-conversation": Notify each time a conversation is updated via
  /// UpdateConversation.
  /// * "upload-conversation": Notify when an UploadConversation LRO is complete.
  ///
  /// Values are Pub/Sub topics. The format of each Pub/Sub topic is:
  /// projects/{project}/topics/{topic}
  public var pubsubNotificationSettings: [Swift.String: Swift.String] = [:]

  /// Default analysis settings.
  public var analysisConfig: Settings.AnalysisConfig? = nil

  /// Default DLP redaction resources to be applied while ingesting
  /// conversations. This applies to conversations ingested from the
  /// `UploadConversation` and `IngestConversations` endpoints, including
  /// conversations coming from CCAI Platform.
  public var redactionConfig: RedactionConfig? = nil

  /// Optional. Default Speech-to-Text resources to use while ingesting audio
  /// files. Optional, CCAI Insights will create a default if not provided. This
  /// applies to conversations ingested from the `UploadConversation` and
  /// `IngestConversations` endpoints, including conversations coming from CCAI
  /// Platform.
  public var speechConfig: SpeechConfig? = nil

  /// Initialize a new instance of `Settings`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Settings().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Default configuration when creating Analyses in Insights.
  public struct AnalysisConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Percentage of conversations created using Dialogflow runtime integration
    /// to analyze automatically, between [0, 100].
    public var runtimeIntegrationAnalysisPercentage: Swift.Double = Swift.Double()

    /// Percentage of conversations created using the UploadConversation endpoint
    /// to analyze automatically, between [0, 100].
    public var uploadConversationAnalysisPercentage: Swift.Double = Swift.Double()

    /// To select the annotators to run and the phrase matchers to use
    /// (if any). If not specified, all annotators will be run.
    public var annotatorSelector: AnnotatorSelector? = nil

    /// Initialize a new instance of `AnalysisConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AnalysisConfig().with { $0.runtimeIntegrationAnalysisPercentage = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.contactcenterinsights.v1.Settings.AnalysisConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.Settings"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
