// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Agent Assist Smart Compose suggestion data.
public struct SmartComposeSuggestionData: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The content of the suggestion.
  public var suggestion: Swift.String = Swift.String()

  /// The system's confidence score that this suggestion is a good match for this
  /// conversation, ranging from 0.0 (completely uncertain) to 1.0 (completely
  /// certain).
  public var confidenceScore: Swift.Double = Swift.Double()

  /// Map that contains metadata about the Smart Compose suggestion and the
  /// document from which it originates.
  public var metadata: [Swift.String: Swift.String] = [:]

  /// The name of the answer record.
  /// Format:
  /// projects/{project}/locations/{location}/answerRecords/{answer_record}
  public var queryRecord: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SmartComposeSuggestionData`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SmartComposeSuggestionData().with { $0.suggestion = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let suggestion = CodingKeys(stringValue: "suggestion")
    static let confidenceScore = CodingKeys(stringValue: "confidenceScore")
    static let metadata = CodingKeys(stringValue: "metadata")
    static let queryRecord = CodingKeys(stringValue: "queryRecord")

    static let _knownKeys: Set<Swift.String> = [
      "suggestion",
      "confidenceScore",
      "metadata",
      "queryRecord",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .suggestion) {
      self.suggestion = value
    }
    if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .confidenceScore) {
      self.confidenceScore = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .metadata)
    {
      self.metadata = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .queryRecord) {
      self.queryRecord = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.suggestion, forKey: .suggestion)
    try container.encode(self.confidenceScore, forKey: .confidenceScore)
    try container.encode(self.metadata, forKey: .metadata)
    try container.encode(self.queryRecord, forKey: .queryRecord)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.SmartComposeSuggestionData"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
