// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Metadata for TuneQaScorecardRevision endpoint.
public struct TuneQaScorecardRevisionMetadata: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The time the operation was created.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The time the operation finished running.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The original request.
  public var request: TuneQaScorecardRevisionRequest? = nil

  /// Output only. The results of data validation per question in the request.
  public var qaQuestionDatasetValidationResults:
    [TuneQaScorecardRevisionMetadata.QaQuestionDatasetValidationResult] = []

  /// Output only. The metrics for each QaQuestion in the TuneScorecardRevision
  /// request.
  public var qaQuestionDatasetTuningMetrics:
    [TuneQaScorecardRevisionMetadata.QaQuestionDatasetTuningMetrics] = []

  /// Output only. The percentage of the tuning job that has completed. Always
  /// between 0 and 1 where 0 indicates the job has not started i.e. 0% and 1
  /// indicates the job has completed i.e. 100%.
  public var tuningCompletionRatio: Swift.Double = Swift.Double()

  /// Initialize a new instance of `TuneQaScorecardRevisionMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TuneQaScorecardRevisionMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Contains validation results for a question in the tuning request.
  public struct QaQuestionDatasetValidationResult: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The resource path of the question whose dataset was
    /// evaluated for tuning.
    public var question: Swift.String = Swift.String()

    /// A list of any applicable data validation warnings about the question's
    /// feedback labels.
    public var datasetValidationWarnings: [DatasetValidationWarning] = []

    /// The number of valid feedback labels in the question's dataset.
    public var validFeedbackLabelsCount: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `QaQuestionDatasetValidationResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QaQuestionDatasetValidationResult().with { $0.question = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.TuneQaScorecardRevisionMetadata.QaQuestionDatasetValidationResult"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Contains performance metrics for each QaQuestion in the
  /// TuneScorecardRevision request.
  public struct QaQuestionDatasetTuningMetrics: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The resource path of the question whose dataset was
    /// evaluated for tuning.
    public var question: Swift.String = Swift.String()

    /// Output only. The metrics for the question's dataset.
    public var metrics: TuneQaScorecardRevisionMetadata.QaQuestionDatasetTuningMetrics.Metrics? =
      nil

    /// Initialize a new instance of `QaQuestionDatasetTuningMetrics`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QaQuestionDatasetTuningMetrics().with { $0.question = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Performance metrics for the question's dataset calculated over the tuned
    /// model.
    public struct Metrics: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Accuracy of the question's dataset.
      public var accuracy: Swift.Double = Swift.Double()

      /// Initialize a new instance of `Metrics`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Metrics().with { $0.accuracy = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.contactcenterinsights.v1.TuneQaScorecardRevisionMetadata.QaQuestionDatasetTuningMetrics.Metrics"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.contactcenterinsights.v1.TuneQaScorecardRevisionMetadata.QaQuestionDatasetTuningMetrics"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.contactcenterinsights.v1.TuneQaScorecardRevisionMetadata"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
