// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// The metadata for an `UploadConversation` operation.
public struct UploadConversationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The time the operation was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time the operation finished running.
  public var endTime: GoogleWKT.Timestamp? = nil

  /// Output only. The original request.
  public var request: UploadConversationRequest? = nil

  /// Output only. The operation name for a successfully created analysis
  /// operation, if any.
  public var analysisOperation: Swift.String = Swift.String()

  /// Output only. The redaction config applied to the uploaded conversation.
  public var appliedRedactionConfig: RedactionConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `UploadConversationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UploadConversationMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let request = CodingKeys(stringValue: "request")
    static let analysisOperation = CodingKeys(stringValue: "analysisOperation")
    static let appliedRedactionConfig = CodingKeys(stringValue: "appliedRedactionConfig")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "endTime",
      "request",
      "analysisOperation",
      "appliedRedactionConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .endTime)
    self.request = try container.decodeIfPresent(UploadConversationRequest.self, forKey: .request)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .analysisOperation) {
      self.analysisOperation = value
    }
    self.appliedRedactionConfig = try container.decodeIfPresent(
      RedactionConfig.self, forKey: .appliedRedactionConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encodeIfPresent(self.request, forKey: .request)
    try container.encode(self.analysisOperation, forKey: .analysisOperation)
    try container.encodeIfPresent(self.appliedRedactionConfig, forKey: .appliedRedactionConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.contactcenterinsights.v1.UploadConversationMetadata"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
